// Creates a uuid-redirects.js file that redirects sf2e compendium UUIDs to pf2e equivalents.
// This addon only activates when both sf2e and pf2e systems are selected.

import * as p from "@clack/prompts";
import { cyan } from "kolorist";
import { readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Get the module directory from environment variable
const moduleDir = process.env.MODULE_DIR || process.cwd();

// Read the module.json to get module ID and packs
const moduleJsonPath = join(moduleDir, "module.json");
if (!existsSync(moduleJsonPath)) {
  p.log.warn("⚠️ module.json not found, skipping SF2e to PF2e UUID redirects");
  process.exit(0);
}

const moduleJson = JSON.parse(await readFile(moduleJsonPath, "utf8"));
const moduleId = moduleJson.id;
const systems = (moduleJson.relationships?.systems || []).map(s => s.id);
const packs = moduleJson.packs || [];

// Check if both sf2e and pf2e are selected
if (!systems.includes("sf2e") || !systems.includes("pf2e")) {
  p.note("⏭️ Skipped - both sf2e and pf2e systems must be selected", "SF2e to PF2e UUID Redirects");
  process.exit(0);
}

// Find base pack names (e.g., "items", "actors") that have both sf2e and pf2e variants
const sf2ePackNames = packs.filter(p => p.system === "sf2e").map(p => p.name.replace("sf2e-", ""));
const pf2ePackNames = packs.filter(p => p.system === "pf2e").map(p => p.name.replace("pf2e-", ""));
const commonPackNames = sf2ePackNames.filter(name => pf2ePackNames.includes(name));

if (commonPackNames.length === 0) {
  p.note("⏭️ Skipped - no common packs found between sf2e and pf2e", "SF2e to PF2e UUID Redirects");
  process.exit(0);
}

// Build the UUID_REDIRECTS object
const redirects = {};
for (const packName of commonPackNames) {
  redirects[`Compendium.${moduleId}.sf2e-${packName}`] = `Compendium.${moduleId}.pf2e-${packName}`;
}

// Generate the uuid-redirects.js content
const redirectsContent = `// Auto-generated by create-fvtt-module - sf2e-pf2e-redirects addon
// Redirects sf2e compendium UUIDs to their pf2e equivalents

Hooks.once("ready", () => {
  if (game.system.id === "sf2e") {
    const UUID_REDIRECTS = {
      ${Object.entries(redirects).map(([from, to]) => `  "${from}": "${to}"`).join(",\n")}
    };

    for (const [from, to] of Object.entries(UUID_REDIRECTS)) {
      CONFIG.compendium.uuidRedirects[from] = to;
    }
  }
});
`;

// Check if src directory exists
const srcDir = join(moduleDir, "src");
const srcExists = existsSync(srcDir);

// Check for index files
const indexTs = join(srcDir, "index.ts");
const indexJs = join(srcDir, "index.js");
const indexTsExists = existsSync(indexTs);
const indexJsExists = existsSync(indexJs);

if (srcExists) {
  // Determine file extension based on existing index files
  const useTypeScript = indexTsExists;
  const redirectFileName = useTypeScript ? "uuid-redirects.ts" : "uuid-redirects.js";
  const importFileName = useTypeScript ? "uuid-redirects.js" : "uuid-redirects.js"; // Always import as .js (TS compilers handle this)
  const redirectsPath = join(srcDir, redirectFileName);

  await writeFile(redirectsPath, redirectsContent);
  p.log.success(`Created ${cyan("src/" + redirectFileName)}`);

  // Try to import into index.ts or index.js
  const importStatement = `import "./${importFileName}";`;

  if (indexTsExists) {
    const indexContent = await readFile(indexTs, "utf8");
    // Check if import already exists
    if (!indexContent.includes("uuid-redirects")) {
      const newIndexContent = `${importStatement}\n${indexContent}`;
      await writeFile(indexTs, newIndexContent);
      p.log.success(`Imported ${redirectFileName} into ${cyan("src/index.ts")}`);
    } else {
      p.log.info(`Import already exists in ${cyan("src/index.ts")}`);
    }
  } else if (indexJsExists) {
    const indexContent = await readFile(indexJs, "utf8");
    if (!indexContent.includes("uuid-redirects")) {
      const newIndexContent = `${importStatement}\n${indexContent}`;
      await writeFile(indexJs, newIndexContent);
      p.log.success(`Imported ${redirectFileName} into ${cyan("src/index.js")}`);
    } else {
      p.log.info(`Import already exists in ${cyan("src/index.js")}`);
    }
  } else {
    p.log.warn(`⚠️ No index.ts or index.js found in src/. Please manually add ${cyan(importStatement)} to your main entry file.`);
  }
} else {
  // No src directory - write to module root and warn
  const redirectsPath = join(moduleDir, "uuid-redirects.js");
  await writeFile(redirectsPath, redirectsContent);
  p.log.warn(`⚠️ No src/ directory found. Created ${cyan("uuid-redirects.js")} in module root.`);
  p.log.warn(`⚠️ Please manually add ${cyan('import "./uuid-redirects.js";')} to your module's main entry point.`);
}

let note = "✅ Installed!";
note += `\n${commonPackNames.length} pack(s) configured for sf2e → pf2e redirect: ${cyan(commonPackNames.join(", "))}`;

p.note(note, "SF2e to PF2e UUID Redirects");
